"""Sync endpoints (Track B — app → Zoho).

All routes require the internal API key and an ``Idempotency-Key`` header.
The key must be a UUID v4 generated by the caller; replays within the TTL
return the cached response without re-calling Zoho.
"""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, Header, status

from app.core.exceptions import ValidationError
from app.dependencies.auth import require_internal_api_key
from app.dependencies.sync import get_sync_service
from app.schemas.sync import (
    CustomerSyncRequest,
    ItemSyncRequest,
    LeadSyncRequest,
    PurchaseOrderSyncRequest,
    SalesOrderSyncRequest,
    SyncResponse,
    VendorSyncRequest,
)
from app.services.sync_service import SyncService

router = APIRouter(
    prefix="/sync",
    tags=["sync"],
    dependencies=[Depends(require_internal_api_key)],
)

SyncSvc = Annotated[SyncService, Depends(get_sync_service)]


def _require_idempotency_key(
    x_idempotency_key: Annotated[str | None, Header(alias="Idempotency-Key")] = None,
) -> str:
    if not x_idempotency_key:
        raise ValidationError("Idempotency-Key header is required")
    return x_idempotency_key


IdempotencyKey = Annotated[str, Depends(_require_idempotency_key)]


@router.post(
    "/customers",
    response_model=SyncResponse,
    status_code=status.HTTP_200_OK,
    summary="Push a Customer record to Zoho Accounts",
)
async def sync_customer(
    req: CustomerSyncRequest,
    service: SyncSvc,
    idempotency_key: IdempotencyKey,
) -> SyncResponse:
    """Create or update the Zoho Account that mirrors this Customer."""
    return await service.sync_customer(req, idempotency_key)


@router.post(
    "/vendors",
    response_model=SyncResponse,
    status_code=status.HTTP_200_OK,
    summary="Push a Vendor record to Zoho Vendors",
)
async def sync_vendor(
    req: VendorSyncRequest,
    service: SyncSvc,
    idempotency_key: IdempotencyKey,
) -> SyncResponse:
    """Create or update the Zoho Vendor that mirrors this Vendor."""
    return await service.sync_vendor(req, idempotency_key)


@router.post(
    "/items",
    response_model=SyncResponse,
    status_code=status.HTTP_200_OK,
    summary="Push an Item record to Zoho Products",
)
async def sync_item(
    req: ItemSyncRequest,
    service: SyncSvc,
    idempotency_key: IdempotencyKey,
) -> SyncResponse:
    """Create or update the Zoho Product that mirrors this Item."""
    return await service.sync_item(req, idempotency_key)


@router.post(
    "/sales-orders",
    response_model=SyncResponse,
    status_code=status.HTTP_200_OK,
    summary="Push a SalesOrder record to Zoho Sales Orders",
)
async def sync_sales_order(
    req: SalesOrderSyncRequest,
    service: SyncSvc,
    idempotency_key: IdempotencyKey,
) -> SyncResponse:
    """Create or update the Zoho Sales Order that mirrors this SalesOrder.

    The Customer and all line-item Items must already be synced (their Zoho ids
    must exist in crm_mappings) before this call succeeds.
    """
    return await service.sync_sales_order(req, idempotency_key)


@router.post(
    "/leads",
    response_model=SyncResponse,
    status_code=status.HTTP_200_OK,
    summary="Push a Lead record to Zoho Leads",
)
async def sync_lead(
    req: LeadSyncRequest,
    service: SyncSvc,
    idempotency_key: IdempotencyKey,
) -> SyncResponse:
    """Create or update the Zoho Lead that mirrors this app Lead."""
    return await service.sync_lead(req, idempotency_key)


@router.post(
    "/purchase-orders",
    response_model=SyncResponse,
    status_code=status.HTTP_200_OK,
    summary="Push a PurchaseOrder record to Zoho Purchase Orders",
)
async def sync_purchase_order(
    req: PurchaseOrderSyncRequest,
    service: SyncSvc,
    idempotency_key: IdempotencyKey,
) -> SyncResponse:
    """Create or update the Zoho Purchase Order that mirrors this PurchaseOrder.

    The Vendor and all line-item Items must already be synced before this call.
    """
    return await service.sync_purchase_order(req, idempotency_key)
