"""add stock_movements table

Revision ID: 0fe7e33f61e6
Revises: d3ac7b94f345
Create Date: 2026-05-31 17:34:34.121976

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0fe7e33f61e6'
down_revision: str | None = 'd3ac7b94f345'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='movement_direction'), nullable=False),
    sa.Column('reason', sa.Enum('PURCHASE', 'SALE', 'ADJUSTMENT', name='movement_reason'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_before', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_after', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(reference_type IS NULL AND reference_id IS NULL) OR (reference_type IS NOT NULL AND reference_id IS NOT NULL)', name='ck_stock_movements_reference_consistency'),
    sa.CheckConstraint('quantity > 0', name='ck_stock_movements_quantity_positive'),
    sa.CheckConstraint('stock_after >= 0', name='ck_stock_movements_stock_after_non_negative'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_created_by_user_id'), 'stock_movements', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_direction'), 'stock_movements', ['direction'], unique=False)
    op.create_index(op.f('ix_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False)
    op.create_index('ix_stock_movements_item_id_created_at', 'stock_movements', ['item_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_reason'), 'stock_movements', ['reason'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_reason'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_item_id_created_at', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_item_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_direction'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_by_user_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.drop_table('stock_movements')
    # ### end Alembic commands ###
