"""add batch_id to sales_order_items

Revision ID: a3f9c1d27e54
Revises: e7b2a9c4d1f8
Create Date: 2026-06-15 00:00:00.000000

SO batch selection (#9) — **purely additive**, no behaviour change for
existing data. A sales-order line may now name the lot it ships from.

* ``sales_order_items`` gains a nullable ``batch_id`` FK → ``batches.id``
  (``ON DELETE RESTRICT``, indexed). NULL means "ship First-Expiry-First-Out"
  — the existing, unchanged behaviour, so every existing line stays valid.

Hand-written (not autogenerated): the project's ``uv run`` path is blocked
by local Application Control, so this revision was authored to match the
conventions of the existing migrations.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3f9c1d27e54"
down_revision: str | None = "e7b2a9c4d1f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("sales_order_items", sa.Column("batch_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_sales_order_items_batch_id_batches",
        "sales_order_items",
        "batches",
        ["batch_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        op.f("ix_sales_order_items_batch_id"),
        "sales_order_items",
        ["batch_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_sales_order_items_batch_id"), table_name="sales_order_items")
    op.drop_constraint(
        "fk_sales_order_items_batch_id_batches",
        "sales_order_items",
        type_="foreignkey",
    )
    op.drop_column("sales_order_items", "batch_id")
