"""add intelligence-layer customer + item fields (Phase 2A.1)

Revision ID: b8d4f2a17c93
Revises: a3f9c1d27e54
Create Date: 2026-06-16 00:00:00.000000

Phase 2A.1 of the intelligence layer — **purely additive**, no behaviour
change to Phase 1. See ``INTELLIGENCE_SPECIFICATION.md`` §3.5–§3.6 and
``AI_Intelligence_Implementation.md`` §3.

What this does:

* New enum types ``customer_type`` (DEALER/SUB_DEALER/RETAILER) and
  ``competitive_risk_level`` (NONE/LOW/MEDIUM/HIGH).
* ``customers`` gains ``customer_type`` (NOT NULL, server default RETAILER —
  so existing rows backfill automatically), structured location columns
  ``state``/``district``/``city``/``pincode`` (all nullable), and
  ``competitive_risk_level`` (NOT NULL, server default NONE).
* ``items`` gains a nullable ``standard_cost`` column with a non-negative
  CHECK constraint (mirrors the other ``items`` money CHECKs).

Hand-written (not autogenerated) to match the conventions of the existing
migrations — the project's ``uv run`` path is blocked by local Application
Control, so revisions are authored directly.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b8d4f2a17c93"
down_revision: str | None = "a3f9c1d27e54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Enum types are created explicitly (create_type=False) so the column DDL
# below never tries to CREATE TYPE a second time.
customer_type = postgresql.ENUM(
    "DEALER", "SUB_DEALER", "RETAILER",
    name="customer_type",
    create_type=False,
)
competitive_risk_level = postgresql.ENUM(
    "NONE", "LOW", "MEDIUM", "HIGH",
    name="competitive_risk_level",
    create_type=False,
)

_ALL_ENUMS = (customer_type, competitive_risk_level)


def upgrade() -> None:
    bind = op.get_bind()
    for enum in _ALL_ENUMS:
        enum.create(bind, checkfirst=True)

    # --- customers: intelligence-layer attributes -------------------------
    # server_default backfills existing rows; NOT NULL is therefore safe to
    # apply in the same statement.
    op.add_column(
        "customers",
        sa.Column("customer_type", customer_type, server_default="RETAILER", nullable=False),
    )
    op.add_column("customers", sa.Column("state", sa.String(length=120), nullable=True))
    op.add_column("customers", sa.Column("district", sa.String(length=120), nullable=True))
    op.add_column("customers", sa.Column("city", sa.String(length=120), nullable=True))
    op.add_column("customers", sa.Column("pincode", sa.String(length=20), nullable=True))
    op.add_column(
        "customers",
        sa.Column(
            "competitive_risk_level",
            competitive_risk_level,
            server_default="NONE",
            nullable=False,
        ),
    )

    # --- items: cost basis ------------------------------------------------
    op.add_column("items", sa.Column("standard_cost", sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_check_constraint(
        "ck_items_standard_cost_non_negative",
        "items",
        "standard_cost IS NULL OR standard_cost >= 0",
    )


def downgrade() -> None:
    bind = op.get_bind()

    op.drop_constraint("ck_items_standard_cost_non_negative", "items", type_="check")
    op.drop_column("items", "standard_cost")

    op.drop_column("customers", "competitive_risk_level")
    op.drop_column("customers", "pincode")
    op.drop_column("customers", "city")
    op.drop_column("customers", "district")
    op.drop_column("customers", "state")
    op.drop_column("customers", "customer_type")

    # Enum types last — after every column that uses them is gone.
    for enum in reversed(_ALL_ENUMS):
        enum.drop(bind, checkfirst=True)
