"""add vendor_item_terms table

Revision ID: d3ac7b94f345
Revises: cca111eadef9
Create Date: 2026-05-31 15:54:46.782409

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd3ac7b94f345'
down_revision: str | None = 'cca111eadef9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=160), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_privileged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('customer_code', sa.String(length=60), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_company_name'), 'customers', ['company_name'], unique=False)
    op.create_index(op.f('ix_customers_created_by_user_id'), 'customers', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_index(op.f('ix_customers_gstin'), 'customers', ['gstin'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(length=160), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('vendor_code', sa.String(length=60), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_created_by_user_id'), 'vendors', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_vendors_gstin'), 'vendors', ['gstin'], unique=True)
    op.create_index(op.f('ix_vendors_vendor_code'), 'vendors', ['vendor_code'], unique=True)
    op.create_index(op.f('ix_vendors_vendor_name'), 'vendors', ['vendor_name'], unique=False)
    op.create_table('vendor_item_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name='ck_vendor_item_terms_discount_percent_range'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_vendor_item_terms_effective_dates_ordered'),
    sa.CheckConstraint('rate >= 0', name='ck_vendor_item_terms_rate_non_negative'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_item_terms_created_by_user_id'), 'vendor_item_terms', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_vendor_item_terms_item_id'), 'vendor_item_terms', ['item_id'], unique=False)
    op.create_index(op.f('ix_vendor_item_terms_vendor_id'), 'vendor_item_terms', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_item_terms_vendor_id'), table_name='vendor_item_terms')
    op.drop_index(op.f('ix_vendor_item_terms_item_id'), table_name='vendor_item_terms')
    op.drop_index(op.f('ix_vendor_item_terms_created_by_user_id'), table_name='vendor_item_terms')
    op.drop_table('vendor_item_terms')
    op.drop_index(op.f('ix_vendors_vendor_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_vendor_code'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_gstin'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_created_by_user_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_customers_gstin'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_by_user_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
