"""add pharma batch + raw/finished item detail tables

Revision ID: e7b2a9c4d1f8
Revises: 4be90595bc88
Create Date: 2026-06-12 00:00:00.000000

Phase 0 of the pharmaceutical-inventory upgrade — **purely additive**, no
behaviour change. See ``proposal.md``.

What this does:

* New enum types: ``storage_condition``, ``material_classification``,
  ``pharmacopoeia``, ``dosage_form``, ``drug_schedule``, ``batch_status``.
* ``items`` gains common-pharma columns ``storage_condition`` /
  ``shelf_life_days`` (both nullable — existing rows and create calls that
  omit them stay valid).
* New 1:1 detail tables ``raw_item_details`` / ``finished_item_details``
  (PK == FK to ``items.id``, ON DELETE CASCADE).
* New ``batches`` table (the lot ledger).
* ``stock_movements`` gains a nullable ``batch_id`` FK.
* **Backfill:** one detail row per existing item, by ``type``, copying the
  item's audit user-ids. A guard raises if any item is left unclassified.

Hand-written (not autogenerated): the project's ``uv run`` path is blocked
by local Application Control, so this revision was authored to match the
conventions of the existing migrations.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7b2a9c4d1f8"
down_revision: str | None = "4be90595bc88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Enum types are created explicitly (create_type=False) so the table /
# column DDL below never tries to CREATE TYPE a second time.
storage_condition = postgresql.ENUM(
    "AMBIENT", "COLD_CHAIN_2_8", "FROZEN", "CONTROLLED",
    name="storage_condition",
    create_type=False,
)
material_classification = postgresql.ENUM(
    "API", "EXCIPIENT", "SOLVENT", "REAGENT", "PACKAGING",
    name="material_classification",
    create_type=False,
)
pharmacopoeia = postgresql.ENUM(
    "IP", "BP", "USP", "EP", "JP", "NONE",
    name="pharmacopoeia",
    create_type=False,
)
dosage_form = postgresql.ENUM(
    "TABLET", "CAPSULE", "SYRUP", "SUSPENSION", "INJECTION", "OINTMENT",
    "CREAM", "GEL", "DROPS", "POWDER", "INHALER", "OTHER",
    name="dosage_form",
    create_type=False,
)
drug_schedule = postgresql.ENUM(
    "NONE", "H", "H1", "X",
    name="drug_schedule",
    create_type=False,
)
batch_status = postgresql.ENUM(
    "QUARANTINE", "RELEASED", "EXPIRED", "REJECTED", "RECALLED",
    name="batch_status",
    create_type=False,
)

_ALL_ENUMS = (
    storage_condition,
    material_classification,
    pharmacopoeia,
    dosage_form,
    drug_schedule,
    batch_status,
)


def upgrade() -> None:
    bind = op.get_bind()
    for enum in _ALL_ENUMS:
        enum.create(bind, checkfirst=True)

    # --- items: common-pharma columns -------------------------------------
    op.add_column("items", sa.Column("storage_condition", storage_condition, nullable=True))
    op.add_column("items", sa.Column("shelf_life_days", sa.Integer(), nullable=True))
    op.create_check_constraint(
        "ck_items_shelf_life_days_non_negative",
        "items",
        "shelf_life_days IS NULL OR shelf_life_days >= 0",
    )

    # --- raw_item_details (1:1 with items) --------------------------------
    op.create_table(
        "raw_item_details",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("material_classification", material_classification, nullable=True),
        sa.Column("pharmacopoeia", pharmacopoeia, nullable=True),
        sa.Column("is_hazardous", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("updated_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("item_id"),
    )
    op.create_index(
        op.f("ix_raw_item_details_created_by_user_id"),
        "raw_item_details",
        ["created_by_user_id"],
        unique=False,
    )

    # --- finished_item_details (1:1 with items) ---------------------------
    op.create_table(
        "finished_item_details",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("generic_name", sa.String(length=255), nullable=True),
        sa.Column("brand_name", sa.String(length=255), nullable=True),
        sa.Column("strength", sa.String(length=64), nullable=True),
        sa.Column("dosage_form", dosage_form, nullable=True),
        sa.Column("pack_size", sa.String(length=64), nullable=True),
        sa.Column("ingredients", sa.Text(), nullable=True),
        sa.Column("container_specification", sa.String(length=255), nullable=True),
        sa.Column("selling_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("license_number", sa.String(length=64), nullable=True),
        sa.Column("registration_code", sa.String(length=64), nullable=True),
        sa.Column("mrp", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("drug_schedule", drug_schedule, nullable=True),
        sa.Column("is_prescription_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("updated_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "selling_price IS NULL OR selling_price >= 0",
            name="ck_finished_item_details_selling_price_non_negative",
        ),
        sa.CheckConstraint(
            "mrp IS NULL OR mrp >= 0",
            name="ck_finished_item_details_mrp_non_negative",
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("item_id"),
    )
    op.create_index(
        op.f("ix_finished_item_details_created_by_user_id"),
        "finished_item_details",
        ["created_by_user_id"],
        unique=False,
    )

    # --- batches (the lot ledger) -----------------------------------------
    op.create_table(
        "batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("batch_number", sa.String(length=64), nullable=False),
        sa.Column("batch_status", batch_status, server_default="QUARANTINE", nullable=False),
        sa.Column("batch_received_date", sa.Date(), nullable=True),
        sa.Column("manufacturing_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=4), server_default="0", nullable=False),
        sa.Column("initial_quantity", sa.Numeric(precision=20, scale=4), server_default="0", nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("storage_location", sa.String(length=120), nullable=True),
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column("received_via_po_id", sa.UUID(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("updated_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("quantity >= 0", name="ck_batches_quantity_non_negative"),
        sa.CheckConstraint("initial_quantity >= 0", name="ck_batches_initial_quantity_non_negative"),
        sa.CheckConstraint("unit_cost IS NULL OR unit_cost >= 0", name="ck_batches_unit_cost_non_negative"),
        sa.CheckConstraint(
            "manufacturing_date IS NULL OR expiry_date >= manufacturing_date",
            name="ck_batches_expiry_after_manufacture",
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["received_via_po_id"], ["purchase_orders.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "batch_number", name="uq_batches_item_id_batch_number"),
    )
    op.create_index(op.f("ix_batches_item_id"), "batches", ["item_id"], unique=False)
    op.create_index(op.f("ix_batches_batch_status"), "batches", ["batch_status"], unique=False)
    op.create_index(op.f("ix_batches_expiry_date"), "batches", ["expiry_date"], unique=False)
    op.create_index(op.f("ix_batches_vendor_id"), "batches", ["vendor_id"], unique=False)
    op.create_index(op.f("ix_batches_received_via_po_id"), "batches", ["received_via_po_id"], unique=False)
    op.create_index(op.f("ix_batches_created_by_user_id"), "batches", ["created_by_user_id"], unique=False)
    op.create_index("ix_batches_item_id_expiry_date", "batches", ["item_id", "expiry_date"], unique=False)

    # --- stock_movements: nullable batch link -----------------------------
    op.add_column("stock_movements", sa.Column("batch_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_stock_movements_batch_id_batches",
        "stock_movements",
        "batches",
        ["batch_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        op.f("ix_stock_movements_batch_id"),
        "stock_movements",
        ["batch_id"],
        unique=False,
    )

    # --- backfill: one detail row per existing item, by type --------------
    # Copies the item's own audit user-ids so the detail row's NOT NULL
    # audit FKs are satisfied without inventing a user.
    op.execute(
        """
        INSERT INTO raw_item_details
            (item_id, is_hazardous, created_by_user_id, updated_by_user_id, created_at, updated_at)
        SELECT id, false, created_by_user_id, updated_by_user_id, now(), now()
        FROM items
        WHERE type = 'RAW'
        """
    )
    op.execute(
        """
        INSERT INTO finished_item_details
            (item_id, is_prescription_required, created_by_user_id, updated_by_user_id, created_at, updated_at)
        SELECT id, false, created_by_user_id, updated_by_user_id, now(), now()
        FROM items
        WHERE type = 'FINISHED'
        """
    )
    # Guard: fail loudly if any item was left without a detail row (would
    # only happen if an item carried an unexpected `type`).
    op.execute(
        """
        DO $$
        DECLARE
            missing integer;
        BEGIN
            SELECT count(*) INTO missing
            FROM items i
            WHERE NOT EXISTS (SELECT 1 FROM raw_item_details r WHERE r.item_id = i.id)
              AND NOT EXISTS (SELECT 1 FROM finished_item_details f WHERE f.item_id = i.id);
            IF missing > 0 THEN
                RAISE EXCEPTION
                    'Phase-0 backfill incomplete: % item(s) have no detail row', missing;
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    bind = op.get_bind()

    op.drop_index(op.f("ix_stock_movements_batch_id"), table_name="stock_movements")
    op.drop_constraint("fk_stock_movements_batch_id_batches", "stock_movements", type_="foreignkey")
    op.drop_column("stock_movements", "batch_id")

    # DROP TABLE removes the table's own indexes/constraints in Postgres.
    op.drop_table("batches")
    op.drop_table("finished_item_details")
    op.drop_table("raw_item_details")

    op.drop_constraint("ck_items_shelf_life_days_non_negative", "items", type_="check")
    op.drop_column("items", "shelf_life_days")
    op.drop_column("items", "storage_condition")

    # Enum types last — after every column that uses them is gone.
    for enum in reversed(_ALL_ENUMS):
        enum.drop(bind, checkfirst=True)
