"""Purchase-order ORM models — header + line items.

A PO captures a buy commitment to a vendor. Lifecycle is deliberately
small for Phase 1:

::

    DRAFT ──receive──▶ RECEIVED  (terminal)

There is no ``APPROVED`` gate, no ``CANCELLED`` state, no edit path.
Wrong DRAFTs simply sit; this can be expanded later without breaking
the contract (adding new enum values + a service transition is
additive). The single state-changing endpoint is ``POST /receive``,
which (atomically): increments item stock for every line, writes one
``stock_movements`` row per line, sets ``status=RECEIVED`` and
``received_date``.

DB-level invariants (CLAUDE.md §10.3 — the safety net beneath the
service layer):

- ``subtotal >= 0`` and ``total >= 0`` — no negative purchase value.
- ``status`` ↔ ``received_date`` consistency:
  ``RECEIVED`` ⇔ ``received_date IS NOT NULL`` and conversely. A row
  cannot be RECEIVED without a date, nor DRAFT with one set.
- On lines: ``quantity > 0``, ``unit_price >= 0``, ``line_total >= 0``.
- ``UNIQUE (purchase_order_id, item_id)`` — no duplicate items per PO;
  the service rejects the payload earlier, this is the backstop.

The ``po_number`` is generated by the Postgres SEQUENCE
``purchase_order_number_seq`` formatted ``PO-YYYYMM-NNNNNN``. The
sequence is non-transactional by design: a rolled-back PO still
consumes a number, leaving a visible gap which is acceptable here —
human-readable monotonicity matters more than gapless numbering.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal
from enum import StrEnum

from sqlalchemy import (
    CheckConstraint,
    Date,
    DateTime,
    Enum,
    ForeignKey,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class PurchaseOrderStatus(StrEnum):
    """Lifecycle states a PO can occupy.

    ``DRAFT`` is the default on insert. ``RECEIVED`` is set by the
    receive flow, which is the only legal transition out of DRAFT in
    Phase 1.
    """

    DRAFT = "DRAFT"
    RECEIVED = "RECEIVED"


class PurchaseOrder(Base):
    """Header for a purchase order placed with a vendor."""

    __tablename__ = "purchase_orders"
    __table_args__ = (
        CheckConstraint("subtotal >= 0", name="ck_purchase_orders_subtotal_non_negative"),
        CheckConstraint("total >= 0", name="ck_purchase_orders_total_non_negative"),
        # The state ↔ received_date invariant. Cannot be RECEIVED
        # without a date; cannot be DRAFT with one set.
        CheckConstraint(
            "(status = 'RECEIVED' AND received_date IS NOT NULL) "
            "OR (status = 'DRAFT' AND received_date IS NULL)",
            name="ck_purchase_orders_status_received_date_consistency",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    # Human-readable identifier — generated by the
    # ``purchase_order_number_seq`` Postgres sequence and formatted
    # ``PO-YYYYMM-NNNNNN`` in the service.
    po_number: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        index=True,
        nullable=False,
    )
    vendor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("vendors.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    order_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        server_default=func.current_date(),
    )
    expected_delivery_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    # NULL while DRAFT; set to today when ``receive`` flips status.
    received_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    status: Mapped[PurchaseOrderStatus] = mapped_column(
        Enum(
            PurchaseOrderStatus,
            name="purchase_order_status",
            values_callable=lambda e: [m.value for m in e],
        ),
        nullable=False,
        index=True,
        default=PurchaseOrderStatus.DRAFT,
        server_default=PurchaseOrderStatus.DRAFT.value,
    )

    # Money columns — 14,2 matches the schema diagram and the
    # vendor_item_terms.rate precision. ``total`` is reserved for the
    # future addition of tax/header-level discounts; for Phase 1 it
    # always equals ``subtotal`` but the column exists so adding tax
    # later doesn't require a migration that backfills it.
    subtotal: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)
    total: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)

    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Audit per CLAUDE.md §10.2.
    created_by_user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    updated_by_user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # ``lazy='selectin'`` is fine here: lines are always wanted with the
    # header (read endpoints, receive flow). Avoids N+1 without forcing
    # callers to remember to ``selectinload``.
    items: Mapped[list[PurchaseOrderItem]] = relationship(
        "PurchaseOrderItem",
        back_populates="purchase_order",
        cascade="all, delete-orphan",
        lazy="selectin",
        order_by="PurchaseOrderItem.created_at",
    )


class PurchaseOrderItem(Base):
    """A single line on a purchase order.

    Immutable once written — there is no ``updated_at`` and no edit
    path. The pair ``(purchase_order_id, item_id)`` is unique at the
    DB level so a duplicate line cannot land even via a buggy service.
    """

    __tablename__ = "purchase_order_items"
    __table_args__ = (
        CheckConstraint("quantity > 0", name="ck_purchase_order_items_quantity_positive"),
        CheckConstraint(
            "unit_price >= 0",
            name="ck_purchase_order_items_unit_price_non_negative",
        ),
        CheckConstraint(
            "line_total >= 0",
            name="ck_purchase_order_items_line_total_non_negative",
        ),
        UniqueConstraint(
            "purchase_order_id",
            "item_id",
            name="uq_purchase_order_items_purchase_order_id_item_id",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    purchase_order_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("purchase_orders.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    item_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("items.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    quantity: Mapped[Decimal] = mapped_column(Numeric(14, 3), nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)
    line_total: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    purchase_order: Mapped[PurchaseOrder] = relationship(
        "PurchaseOrder",
        back_populates="items",
    )
