"""Sales-order ORM models — header + line items.

Symmetric to :mod:`app.models.purchase_order` but for the OUT direction.
Lifecycle is again deliberately small for Phase 1:

::

    DRAFT ──ship──▶ SHIPPED  (terminal)

There is no ``CANCELLED`` state, no edit path, no PATCH/DELETE on the
API. The single state-changing endpoint is ``POST /ship``, which
(atomically): decrements item stock for every line, writes one
``stock_movements`` row per line, sets ``status=SHIPPED`` and
``shipped_date``.

DB-level invariants (CLAUDE.md §10.3):

- ``subtotal >= 0`` and ``total >= 0``
- ``status`` ↔ ``shipped_date`` consistency:
  ``SHIPPED`` ⇔ ``shipped_date IS NOT NULL`` and conversely.
- On lines: ``quantity > 0``, ``unit_price >= 0``, ``line_total >= 0``.
- ``UNIQUE (sales_order_id, item_id)`` — no duplicate lines per SO.

The ``so_number`` is generated by the Postgres SEQUENCE
``sales_order_number_seq`` formatted ``SO-YYYYMM-NNNNNN`` — same trade-off
as the PO sequence (non-transactional, may leave gaps on rollback).

The stock-non-negative invariant on ``items.stock_quantity`` is what
makes the ship flow safe. The DB CHECK on ``stock_movements.stock_after``
together with the ``items`` CHECK provide the final safety net under
:meth:`StockMovementService.record_movement`.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal
from enum import StrEnum

from sqlalchemy import (
    CheckConstraint,
    Date,
    DateTime,
    Enum,
    ForeignKey,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class SalesOrderStatus(StrEnum):
    """Lifecycle states an SO can occupy.

    ``DRAFT`` on insert. ``SHIPPED`` is set by the ship flow — the only
    legal transition out of DRAFT in Phase 1.
    """

    DRAFT = "DRAFT"
    SHIPPED = "SHIPPED"


class SalesOrder(Base):
    """Header for a sales order placed by a customer."""

    __tablename__ = "sales_orders"
    __table_args__ = (
        CheckConstraint("subtotal >= 0", name="ck_sales_orders_subtotal_non_negative"),
        CheckConstraint("total >= 0", name="ck_sales_orders_total_non_negative"),
        CheckConstraint(
            "(status = 'SHIPPED' AND shipped_date IS NOT NULL) "
            "OR (status = 'DRAFT' AND shipped_date IS NULL)",
            name="ck_sales_orders_status_shipped_date_consistency",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    # Human-readable identifier — generated by the
    # ``sales_order_number_seq`` Postgres sequence and formatted
    # ``SO-YYYYMM-NNNNNN`` in the service.
    so_number: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        index=True,
        nullable=False,
    )
    customer_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("customers.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    order_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        server_default=func.current_date(),
    )
    expected_delivery_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    # NULL while DRAFT; set to today when ``ship`` flips status.
    shipped_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    status: Mapped[SalesOrderStatus] = mapped_column(
        Enum(
            SalesOrderStatus,
            name="sales_order_status",
            values_callable=lambda e: [m.value for m in e],
        ),
        nullable=False,
        index=True,
        default=SalesOrderStatus.DRAFT,
        server_default=SalesOrderStatus.DRAFT.value,
    )

    subtotal: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)
    # ``total`` is reserved for the future addition of tax/header
    # discounts; in Phase 1 it always equals ``subtotal``.
    total: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)

    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Audit per CLAUDE.md §10.2.
    created_by_user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    updated_by_user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    items: Mapped[list[SalesOrderItem]] = relationship(
        "SalesOrderItem",
        back_populates="sales_order",
        cascade="all, delete-orphan",
        lazy="selectin",
        order_by="SalesOrderItem.created_at",
    )


class SalesOrderItem(Base):
    """A single line on a sales order. Immutable once written."""

    __tablename__ = "sales_order_items"
    __table_args__ = (
        CheckConstraint("quantity > 0", name="ck_sales_order_items_quantity_positive"),
        CheckConstraint(
            "unit_price >= 0",
            name="ck_sales_order_items_unit_price_non_negative",
        ),
        CheckConstraint(
            "line_total >= 0",
            name="ck_sales_order_items_line_total_non_negative",
        ),
        UniqueConstraint(
            "sales_order_id",
            "item_id",
            name="uq_sales_order_items_sales_order_id_item_id",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    sales_order_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("sales_orders.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    item_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("items.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    quantity: Mapped[Decimal] = mapped_column(Numeric(14, 3), nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)
    line_total: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    sales_order: Mapped[SalesOrder] = relationship(
        "SalesOrder",
        back_populates="items",
    )
